###

POST http://localhost:7777/user/register
Content-Type: application/json

{
  "username": "raju4789",
  "password":"mln1234",
  "email":"narasimha4789@gmail.com",
  "firstname": "Raju",
  "lastname": "MLN"
}

###

POST http://localhost:7777/user/login
Content-Type: application/json

{
  "username": "raju4789",
  "password":"mln1234"
}

###
GET http://localhost:7777/user/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhanUiLCJwYXNzd29yZCI6Im1sbjEyMzQiLCJpYXQiOjE2MDIzMzA0OTQsImV4cCI6MTYwMjMzMDU1NH0.mJZtkyCivB_RvxVZKSF0DOKE7VlvBhA0uSIPMtqflPg


